# Site settings
# Acccessed via {{ site.title }}, {{ site.email }}, {{ site.custom_variable }}
title: Tony Le
email: contact@tonyle.com
description: >- # this means to ignore newlines until "baseurl:"
  This is the website you go to if you want to know who Tony Le is
# baseurl: "" # the subpath of your site, e.g. /blog
url: https://tonyle.com # the base hostname & protocol for your site, e.g. http://example.com
# custom_variable:

# Build settings
theme: just-the-docs
# plugins:
#  - jekyll-feed

search:
  button: true

enable_copy_code_button: true

aux_links:
  "contact@tonyle.com":
    - "mailto:contact@tonyle.com"

back_to_top: false
back_to_top_text: "Back to top"

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/tfle/tfle.github.io"
gh_edit_branch: "main"
gh_edit_view_mode: "edit" # "tree" or "edit"

mermaid:
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.3.0"

callouts_level: quiet # quiet or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
  did-you-know:
    title: Did you know?
    color: green

collections_dir: collections

collections:
  projects:
    permalink: "/:collection/:path/"
    output: true
  classes:
    permalink: "/:collection/:path/"
    output: true
  wiki:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:
    projects:
      name: Projects
      nav_fold: true
    classes:
      name: Classes
      nav_fold: true
    wiki:
      name: Wiki
      nav_fold: true
      # nav_exclude: true
      # search_exclude: true
